version: '3.4'

services:
  api:
    image: ${DOCKER_REGISTRY-}api
    build:
      context: .
      dockerfile: API/Dockerfile
    ports:
    - "8080:8080"
    - "8081:8081"
  mongo:
    image: mongodb/mongodb-community-server:latest
    ports:
    - "27017:27017"
    
