version: '3.4'

services:
  api:
    image: ${DOCKER_REGISTRY-}api
    build:
      context: .
      dockerfile: API/Dockerfile
    ports:
    - "8080:8080"
    - "8081:8081"
    depends_on:
      - email_service
      - mongo
      - garnet
      - rabbit-mq

  email_service:
    image: ${DOCKER_REIGSTRY-}email_service
    build:
      context: .
      dockerfile: Services/Email-Service/Dockerfile
    depends_on:
      - mongo
      - rabbit-mq

  log_service:
    image: ${DOCKER_REIGSTRY-}log_service
    build:
      context: .
      dockerfile: Services/Log-Service/Dockerfile
    depends_on:
      - mongo
      - rabbit-mq

  mongo:
    image: mongodb/mongodb-community-server:latest
    ports:
    - "27017:27017"
    volumes:
    - "C:/data/db:/data/db"

  garnet:
    build:
      context: .
      dockerfile: Garnet/Dockerfile
    ports:
    - "6379:6379"

  rabbit-mq:
    image: rabbitmq:3.13-management
    ports:
    - "15672:15672"
    - "5672:5672" 
    
