version: '3.4'

services:
  api:
    image: ${DOCKER_REGISTRY-}api
    build:
      context: .
      dockerfile: API/Dockerfile
    ports:
    - "8080:8080"
    - "8081:8081"
  mongo:
    image: mongodb/mongodb-community-server:latest
    ports:
    - "27017:27017"
  redis:
    image: redis/redis-stack-server:latest
    ports:
    - "6379:6379"
  rabbit-mq:
    image: rabbitmq:3.13-management
    ports:
    - "5672:5672" 
    
