version: '3.4'

services:
  api:
    image: ${DOCKER_REGISTRY-}api
    build:
      context: .
      dockerfile: API/Dockerfile
    ports:
    - "8080:8080"
    - "8081:8081"
  email_service:
    image: ${DOCKER_REIGSTRY-}email_service
    build:
      context: .
      dockerfile: Services/Email-Service/Dockerfile
  mongo:
    image: mongodb/mongodb-community-server:latest
    ports:
    - "27017:27017"
  redis:
    image: redis/redis-stack-server:latest
    ports:
    - "6379:6379"
  rabbit-mq:
    image: rabbitmq:3.13-management
    ports:
    - "15672:15672"
    - "5672:5672" 
    
